[[call]]
call_type = "invoke"
contract_address = "0x4718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d"
function = "approve"
inputs = ["0x2c56e8b00dbe2a71e57472685378fc8988bba947e9a99b26a00fade2b4fe7c2", "0x2b5e3af16b1880000", "0x0"]

[[call]]
call_type = "invoke"
contract_address = "0x2c56e8b00dbe2a71e57472685378fc8988bba947e9a99b26a00fade2b4fe7c2"
function = "multi_route_swap"
inputs = ["0x4718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d", "0x2b5e3af16b1880000", "0x0", "0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7", "0xca638f68cac11", "0x0", "0xc044fb705a376", "0x0", "0x759a4374389b0e3cfcc59d49310b6bc75bb12bbf8ce550eb5c2f026918bb344", "0x0", "0x0", "0x1", "0x4718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d", "0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7", "0x444a09d96389aa7148f1aada508e30b71299ffe650d9c97fdaae38cb9a23384", "0xe8d4a51000", "0x6", "0x4718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d", "0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7", "0x20c49ba5e353f80000000000000000", "0x3e8", "0x0", "0x31becdb921c800000000000000000"]
