[package]
name = "obelysk_contracts"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.12.0"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts", tag = "v0.20.0" }
sage_contracts = { path = "../../BitSage-Cairo-Smart-Contracts" }

[[target.starknet-contract]]
casm = true
