[sncast.default]
account = "deployer"
accounts-file = "deployment/sncast_accounts.json"
url = "https://starknet-sepolia.g.alchemy.com/starknet/version/rpc/v0_7/demo"

[sncast.mainnet]
account = "deployer-mainnet"
accounts-file = "deployment/sncast_accounts.json"
url = "https://starknet-mainnet.g.alchemy.com/starknet/version/rpc/v0_7/demo"
