[sncast.default]
account = "deployer"
accounts-file = "deployment/sncast_accounts.json"
url = "https://api.cartridge.gg/x/starknet/sepolia"

[sncast.mainnet]
account = "mainnet-deployer"
accounts-file = "deployment/sncast_accounts.json"
